export const PASSENGER_KEYWORDS_LATIN = [
  "taxi",
  "taksi",
  "takis",
  "taxi kerak",
  "taksi kerak",
  "taxi kere",
  "taksi kere",
  "takis kere",
  "mashina kerak",
  "moshina kerak",
  "mashina kere",
  "moshina kere",
  "avto kerak",
  "mashina bormi",
  "taksi bormi",
  "taxi bormi",
  "ketish kerak",
  "borish kerak",
  "olib ketadigan",
  "ob ketadigan",
  "olib ketadigan bormi",
  "ob ketadigan bormi",
  "ketaman",
  "ketamiz",
  "boraman",
  "boramiz",
  "borishim kerak",
  "ketishim kerak",
  "yo'lovchi",
  "yolovchi",
  "yulovchi",
  "poputchik",
  "poputka",
  "joy bormi",
  "bosh joy bormi",
  "bo'sh joy bormi",
  "orqa joy bormi",
  "nechida ketadi",
  "bugun ketish kerak",
  "hozir ketish kerak",
  "kechga ketish kerak",
  "manzilga borishim kerak",
  "shu yerga borishim kerak"
] as const;

export const PASSENGER_KEYWORDS_CYRILLIC = [
  "такси",
  "такси керак",
  "такси кере",
  "такси борми",
  "машина керак",
  "мошина керак",
  "машина кере",
  "мошина кере",
  "авто керак",
  "машина борми",
  "кетиш керак",
  "бориш керак",
  "олиб кетадиган",
  "олиб кетадиган борми",
  "кетаман",
  "кетамиз",
  "бораман",
  "борамиз",
  "боришим керак",
  "кетишим керак",
  "йўловчи",
  "йуловчи",
  "попутчик",
  "попутка",
  "жой борми",
  "бўш жой борми",
  "буш жой борми",
  "орқа жой борми",
  "нечида кетади",
  "бугун кетиш керак",
  "ҳозир кетиш керак",
  "хозир кетиш керак",
  "манзилга боришим керак",
  "шу ерга боришим керак"
] as const;

export const ROUTE_KEYWORDS = [
  "tomon",
  "yo'nalish",
  "yonalish",
  "marshrut",
  "qayerdan",
  "qayerga",
  "dan",
  "ga",
  "tomon ketadi",
  "qaysi tomonga",
  "томон",
  "йўналиш",
  "йуналиш",
  "маршрут",
  "қаердан",
  "каердан",
  "қаерга",
  "каерга",
  "дан",
  "га"
] as const;

export const MOVEMENT_KEYWORDS = [
  "aeroport",
  "aeroportga",
  "airport",
  "vokzal",
  "vokzalga",
  "аеропорт",
  "аэропорт",
  "вокзал",
  "ketadigan",
  "ketadi",
  "boradigan",
  "boradi",
  "olib boring",
  "olib ketish",
  "yetkazib qo'yish",
  "eltib qo'yish",
  "олиб боринг",
  "олиб кетиш",
  "етказиб қўйиш",
  "элтиб қўйиш"
] as const;

export const DRIVER_AD_NEGATIVE_KEYWORDS = [
  "yo'lovchi olamiz",
  "yo'lovchi olaman",
  "yolovchi olamiz",
  "yolovchi olaman",
  "mijoz olamiz",
  "mijoz olaman",
  "klient olamiz",
  "klient olaman",
  "odam olamiz",
  "odam olaman",
  "odam olib ketamiz",
  "odam olib ketaman",
  "odam ob ketaman",
  "bo'sh joy bor",
  "bosh joy bor",
  "1 ta joy bor",
  "2 ta joy bor",
  "3 ta joy bor",
  "1 kishi bor",
  "2 kishi bor",
  "3 kishi bor",
  "joy bor",
  "mashina bor",
  "mashinam bor",
  "moshina bor",
  "moshinam bor",
  "avto bor",
  "tayyor moshina bor",
  "tayyor moshina",
  "olib ketaman",
  "olib ketamiz",
  "olib ketib qo'yaman",
  "olib ketib qoyaman",
  "ob ketaman",
  "ob ketamiz",
  "ob ketib qoyaman",
  "qatnaymiz",
  "har kuni qatnaymiz",
  "ketadiganlar bolsa",
  "ketadiganlar bo'lsa",
  "ketadigan bolsa",
  "ketadigan bo'lsa",
  "taxi xizmati",
  "taksi xizmati",
  "xizmat ko'rsatamiz",
  "taksilarim",
  "taksislarim",
  "aloqaga chiqadi",
  "biroz kuting",
  "kuting",
  "sizga taksilarim",
  "доставим",
  "пассажир оламиз",
  "пассажир оламан",
  "йўловчи оламиз",
  "йўловчи оламан",
  "йуловчи оламиз",
  "йуловчи оламан",
  "мижоз оламиз",
  "мижоз оламан",
  "клиент оламиз",
  "клиент оламан",
  "одам оламиз",
  "одам оламан",
  "бўш жой бор",
  "буш жой бор",
  "жой бор",
  "қатнаймиз",
  "катнаймиз",
  "ҳар куни қатнаймиз",
  "хар куни катнаймиз",
  "такси хизмати"
] as const;

export const SPAM_KEYWORDS = [
  "reklama",
  "aksiya",
  "chegirma",
  "sotiladi",
  "obuna",
  "подписка",
  "продам",
  "скидка",
  "акция",
  "реклама",
  "http://",
  "https://",
  "t.me/",
  "instagram.com",
  "youtube.com"
] as const;

export const DEFAULT_KEYWORDS = {
  latin: [...PASSENGER_KEYWORDS_LATIN],
  cyrillic: [...PASSENGER_KEYWORDS_CYRILLIC],
  route: [...ROUTE_KEYWORDS],
  extra: [...MOVEMENT_KEYWORDS]
} as const;

export const DEFAULT_SPAM_KEYWORDS = [...SPAM_KEYWORDS] as const;
