export const PASSENGER_KEYWORDS_LATIN = [
  "taxi",
  "taksi",
  "taxi kerak",
  "taksi kerak",
  "mashina kerak",
  "moshina kerak",
  "avto kerak",
  "mashina bormi",
  "taksi bormi",
  "taxi bormi",
  "ketish kerak",
  "borish kerak",
  "olib ketadigan",
  "ob ketadigan",
  "olib ketadigan bormi",
  "ob ketadigan bormi",
  "ketaman",
  "ketamiz",
  "boraman",
  "boramiz",
  "borishim kerak",
  "ketishim kerak",
  "yo'lovchi",
  "yolovchi",
  "yulovchi",
  "poputchik",
  "poputka",
  "joy bormi",
  "bosh joy bormi",
  "bo'sh joy bormi",
  "orqa joy bormi",
  "nechida ketadi",
  "bugun ketish kerak",
  "hozir ketish kerak",
  "kechga ketish kerak",
  "manzilga borishim kerak",
  "shu yerga borishim kerak"
] as const;

export const PASSENGER_KEYWORDS_CYRILLIC = [
  "такси",
  "такси керак",
  "такси борми",
  "машина керак",
  "мошина керак",
  "авто керак",
  "машина борми",
  "кетиш керак",
  "бориш керак",
  "олиб кетадиган",
  "олиб кетадиган борми",
  "кетаман",
  "кетамиз",
  "бораман",
  "борамиз",
  "боришим керак",
  "кетишим керак",
  "йўловчи",
  "йуловчи",
  "попутчик",
  "попутка",
  "жой борми",
  "бўш жой борми",
  "буш жой борми",
  "ор?а жой борми",
  "нечида кетади",
  "бугун кетиш керак",
  "?озир кетиш керак",
  "хозир кетиш керак",
  "манзилга боришим керак",
  "шу ерга боришим керак"
] as const;

export const ROUTE_KEYWORDS = [
  "tomon",
  "yo'nalish",
  "yonalish",
  "marshrut",
  "qayerdan",
  "qayerga",
  "dan",
  "ga",
  "tomon ketadi",
  "qaysi tomonga",
  "томон",
  "йўналиш",
  "йуналиш",
  "маршрут",
  "?аердан",
  "каердан",
  "?аерга",
  "каерга",
  "дан",
  "га"
] as const;

export const MOVEMENT_KEYWORDS = [
  "aeroport",
  "aeroportga",
  "airport",
  "vokzal",
  "vokzalga",
  "аеропорт",
  "аэропорт",
  "вокзал",
  "ketadigan",
  "ketadi",
  "boradigan",
  "boradi",
  "olib boring",
  "olib ketish",
  "yetkazib qo'yish",
  "eltib qo'yish",
  "олиб боринг",
  "олиб кетиш",
  "етказиб ?ўйиш",
  "элтиб ?ўйиш"
] as const;

export const DRIVER_AD_NEGATIVE_KEYWORDS = [
  "yo'lovchi olamiz",
  "yolovchi olamiz",
  "mijoz olamiz",
  "klient olamiz",
  "bo'sh joy bor",
  "bosh joy bor",
  "1 ta joy bor",
  "2 ta joy bor",
  "3 ta joy bor",
  "joy bor",
  "qatnaymiz",
  "har kuni qatnaymiz",
  "taxi xizmati",
  "taksi xizmati",
  "xizmat ko'rsatamiz",
  "доставим",
  "пассажир оламиз",
  "йўловчи оламиз",
  "йуловчи оламиз",
  "мижоз оламиз",
  "клиент оламиз",
  "бўш жой бор",
  "буш жой бор",
  "жой бор",
  "?атнаймиз",
  "катнаймиз",
  "?ар куни ?атнаймиз",
  "хар куни катнаймиз",
  "такси хизмати"
] as const;

export const SPAM_KEYWORDS = [
  "reklama",
  "aksiya",
  "chegirma",
  "sotiladi",
  "obuna",
  "подписка",
  "продам",
  "скидка",
  "акция",
  "реклама",
  "http://",
  "https://",
  "t.me/",
  "instagram.com",
  "youtube.com"
] as const;

export const DEFAULT_KEYWORDS = {
  latin: [...PASSENGER_KEYWORDS_LATIN],
  cyrillic: [...PASSENGER_KEYWORDS_CYRILLIC],
  route: [...ROUTE_KEYWORDS],
  extra: [...MOVEMENT_KEYWORDS]
} as const;

export const DEFAULT_SPAM_KEYWORDS = [...SPAM_KEYWORDS] as const;
